name: Update File
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update File
        run: |
          echo $(date '+%Y-%m-%d %H:%M:%S') > Update


      - name: Commit and push changes
        run: |
          git config --global user.name "League of Legends Skin Changer 2025"
          git config --global user.email "lol-skin-changer@github.com"
          git add Update
          git commit -m "Update file"
          git push
